services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: event-booster
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: event-booster
    ports:
      - "5432:5432"